-- Prerequisites
local config = fs.open("config.json", "r")
local configuration = textutils.unserializeJSON(config.readAll())
config.close()

local oreAllowList = configuration.oresAllowList
local CCGUIUrl = "https://raw.githubusercontent.com/LD-Reborn/CC-GUI/refs/heads/main/GUI.lua"
local GUI = {}
local success, result = pcall(function()
    GUI = require("modules/GUI")
end)
if not success then
    shell.execute("wget", CCGUIUrl, "modules/GUI")
    GUI = require("modules/GUI")
end

-- Important functions

local function matchesAllowlistAndGetColor(ore, allowlist)
    if ore == nil then
        return false, nil
    end
    for key, value in pairs(allowlist) do
        match = string.gmatch(ore, key)()
        if match then
            return true, value
        end
    end
    return false, nil
end

local function scanAndFilter(wrappedPeripheral)
    ores = wrappedPeripheral.scan(16)
    for key, value in pairs(ores) do
        success, color = matchesAllowlistAndGetColor(value.name, oreAllowList)
        if not success then
            ores[key] = nil
        else
            ores[key].color = color
        end
    end
    return ores
end

local function isBetween(x, a, b, inclusiveA, inclusiveB)
    local checkA, checkB
    if inclusiveA then
        checkA = x >= a
    else
        checkA = x > a
    end
    if inclusiveB then
        checkB = x <= b
    else
        checkB = x < b
    end
    return checkA and checkB
end

function swapPeripherals()
    pocket.equipBack()
    return peripheral.wrap("back")
end

function getPlayerInfo(wrappedPeripheral)
    local playersInRange
    repeat
        playersInRange = wrappedPeripheral.getPlayersInRange(3)
    until #playersInRange >= 1
    local playerName = playersInRange[1]
    return wrappedPeripheral.getPlayer(playerName)
end

function checkIsGeoDetector(wrappedPeripheral)
    if not wrappedPeripheral then return false end
    return wrappedPeripheral.scan ~= nil
end

function checkIsPlayerDetector(wrappedPeripheral)
    if not wrappedPeripheral then return false end
    return wrappedPeripheral.getPlayersInRange ~= nil and wrappedPeripheral.getPlayer ~= nil
end

function ensureGeoDetector(wrappedPeripheral, depth)
    if depth == nil then
        depth = 0
    end
    if wrappedPeripheral == nil then
       wrappedPeripheral = peripheral.wrap("back") 
    end
    if checkIsGeoDetector(wrappedPeripheral) == false then
        local swapped = swapPeripherals()
        if checkIsGeoDetector(swapped) then
            return swapped
        elseif depth < 10 then
            return ensureGeoDetector(swapped, depth + 1)
        else
            return false
        end
    end
    return wrappedPeripheral
end

function ensurePlayerDetector(wrappedPeripheral, depth)
    if depth == nil then
        depth = 0
    end
    if wrappedPeripheral == nil then
       wrappedPeripheral = peripheral.wrap("back") 
    end
    if checkIsPlayerDetector(wrappedPeripheral) == false then
        local swapped = swapPeripherals()
        if checkIsPlayerDetector(swapped) then
            return swapped
        elseif depth < 10 then
            return ensurePlayerDetector(swapped, depth + 1)
        else
            return false
        end
    end
    return wrappedPeripheral
end

function getDistance(ox, oy, oz, x, y, z)
    diffX = x - ox
    diffY = y - oy
    diffZ = z - oz
    return math.sqrt(diffX * diffX + diffY * diffY + diffZ * diffZ)
end

-- function rotatePoint(x, y, ox, oy, angle): Generated by LLM
local function rotatePoint(x, y, ox, oy, angle)
    local rad = math.rad(angle)
    local cos = math.cos(rad)
    local sin = math.sin(rad)

    -- Translate point back to origin
    local dx = x - ox
    local dy = y - oy

    -- Rotate
    local rx = dx * cos - dy * sin
    local ry = dx * sin + dy * cos

    -- Translate back
    return rx + ox, ry + oy
end

-- Initialize and determine some values
termWidth, termHeight = term.getSize()
termMidX = math.floor(termWidth / 2)
termMidY = math.floor(termHeight / 2)
local playerInfo
local playerPosLastGeo = {0, 0, 0}
local hasGeoDetector = ensureGeoDetector() ~= false
local hasPlayerDetector = ensurePlayerDetector() ~= false
local backPeripheral = ensureGeoDetector()
if not hasGeoDetector then
    print("No Geo Scanner was detected.")
    pocket.unequipBack(backPeripheral)
    return
end
assert(checkIsGeoDetector(backPeripheral))
ores = scanAndFilter(backPeripheral)

if not hasPlayerDetector then
    print("No Player Detector was detected. Continuing without gyroscope.")
    print("\"Up\" on the map aligns with south.")
    sleep(5)
end

-- Create toggle button
toggleButtonWidth = 6
toggleButtonheight = 2
toggleButton = GUI.createButton("scan",
    termWidth - toggleButtonWidth,
    termHeight - toggleButtonheight,
    toggleButtonWidth, toggleButtonheight,
    colors.white, colors.red,
    colors.white, colors.green
)
toggleButton.toggle = true

term.clear()
i = 0
while true do
    if toggleButton.state == true then
        i = i + 1
        if hasPlayerDetector then
            backPeripheral = ensurePlayerDetector(backPeripheral)
            playerInfo = getPlayerInfo(backPeripheral)
        end
        playerPosDiff = {
            playerPosLastGeo[1] - playerInfo.x,
            playerPosLastGeo[2] - playerInfo.y,
            playerPosLastGeo[3] - playerInfo.z
        }
        distanceSinceLastGeo = getDistance(0, 0, 0, playerPosDiff[1], playerPosDiff[2], playerPosDiff[3])
        if i % 8 == 0 or distanceSinceLastGeo > 8 then
            backPeripheral = ensureGeoDetector()
            ores = scanAndFilter(backPeripheral)
            playerPosLastGeo = {playerInfo.x, playerInfo.y, playerInfo.z}
            i = 1
        end
        term.setBackgroundColor(colors.black)
        term.clear()
        for key, value in pairs(ores) do
            -- rotate
            x, y = rotatePoint(value.x + playerPosDiff[1], value.z + playerPosDiff[3], 0, 0, -playerInfo.yaw)
            -- round and diff
            x = termMidX - math.floor(x)
            y = termMidY - math.floor(y)
            local textColor = colors.red
            local backgroundColor = colors.black
            local text
            local relativeY = value.y - playerPosDiff[2]
            if relativeY == 0 then
                textColor = colors.lime
                text = "O"
            elseif isBetween(relativeY, -3, 0, true, false) then
                textColor = colors.green
                text = "v"
            elseif isBetween(relativeY, 0, 3, false, true) then
                textColor = colors.green
                text = "^"
            elseif isBetween(relativeY, -10, -3, true, false) then
                textColor = colors.yellow
                text = "v"
            elseif isBetween(relativeY, 3, 10, false, true) then
                textColor = colors.yellow
                text = "^"
            elseif isBetween(relativeY, -32, -10, true, false) then
                textColor = colors.orange
                text = "v"
            elseif isBetween(relativeY, 10, 32, false, true) then
                textColor = colors.orange
                text = "^"
            end
            -- file = fs.open("test.txt", "w")
            -- file.write(textutils.serialize(value))
            -- file.close()
            -- print(textutils.serialize(value))
            -- sleep(1)
            if text ~= nil and value.color ~= nil then
                backgroundColor = colors[value.color]
                if GUI._2Dhit(x, y, 0, 0, termWidth, termHeight) then
                    GUI.drawText(term, x, y, textColor, backgroundColor, text)
                    GUI.drawText(term, 0, 0, textColor, backgroundColor, text)
                end
            end
        end
        GUI.drawText(term, termMidX, termMidY, colors.black, colors.white, " ") -- Indicate player position
    end
    
    GUI.drawAll(false)
    os.startTimer(0.2) -- Throw in a timer to quickly continue if there are no events queued
    events = {os.pullEvent()}
    GUI.handleEvent(events)
end