-- Prerequisites
local oreAllowList = {
    ["minecraft:ancient_debris"] = colors.black,
    -- ["minecraft:iron_ore"] = colors.gray,
    -- ["minecraft:copper_ore"] = colors.brown,
    ["minecraft:gold_ore"] = colors.yellow,
    ["minecraft:deepslate_gold_ore"] = colors.yellow,
    ["minecraft:diamond_ore"] = colors.blue,
    ["minecraft:deepslate_diamond_ore"] = colors.blue,
    ["minecraft:nether_portal"] = colors.purple,
    ["ae2:quartz_cluster"] = colors.cyan
}
local CCGUIUrl = "https://raw.githubusercontent.com/LD-Reborn/CC-GUI/refs/heads/main/GUI.lua"
local GUI = {}
local success, result = pcall(function()
    GUI = require("modules/GUI")
end)
if not success then
    shell.execute("wget", CCGUIUrl, "modules/GUI")
    GUI = require("modules/GUI")
end

-- Important functions
local function scanAndFilter(wrappedPeripheral)
    ores = wrappedPeripheral.scan(16)
    for key, value in pairs(ores) do
        if oreAllowList[value.name] == nil then
            ores[key] = nil
        end
    end
    return ores
end

local function isBetween(x, a, b, inclusiveA, inclusiveB)
    local checkA, checkB
    if inclusiveA then
        checkA = x >= a
    else
        checkA = x > a
    end
    if inclusiveB then
        checkB = x <= b
    else
        checkB = x < b
    end
    return checkA and checkB
end

function swapPeripherals()
    pocket.equipBack()
    return peripheral.wrap("back")
end

function getPlayerInfo(wrappedPeripheral)
    local playersInRange
    repeat
        playersInRange = wrappedPeripheral.getPlayersInRange(3)
    until #playersInRange >= 1
    local playerName = playersInRange[1]
    return wrappedPeripheral.getPlayer(playerName)
end

function checkIsGeoDetector(wrappedPeripheral)
    return wrappedPeripheral.scan ~= nil
end

function checkIsPlayerDetector(wrappedPeripheral)
    return wrappedPeripheral.getPlayersInRange ~= nil and wrappedPeripheral.getPlayer ~= nil
end

function ensureGeoDetector(wrappedPeripheral, depth)
    if depth == nil then
        depth = 0
    end
    if wrappedPeripheral == nil then
       wrappedPeripheral = peripheral.wrap("back") 
    end
    if checkIsGeoDetector(wrappedPeripheral) == false then
        local swapped = swapPeripherals()
        if checkIsGeoDetector(swapped) then
            return swapped
        elseif depth < 10 then
            return ensureGeoDetector(swapped, depth + 1)
        else
            return false
        end
    end
    return wrappedPeripheral
end

function ensurePlayerDetector(wrappedPeripheral, depth)
    if depth == nil then
        depth = 0
    end
    if wrappedPeripheral == nil then
       wrappedPeripheral = peripheral.wrap("back") 
    end
    if checkIsPlayerDetector(wrappedPeripheral) == false then
        local swapped = swapPeripherals()
        if checkIsPlayerDetector(swapped) then
            return swapped
        elseif depth < 10 then
            return ensurePlayerDetector(swapped, depth + 1)
        else
            return false
        end
    end
    return wrappedPeripheral
end

-- function rotatePoint(x, y, ox, oy, angle): Generated by LLM
local function rotatePoint(x, y, ox, oy, angle)
    local rad = math.rad(angle)
    local cos = math.cos(rad)
    local sin = math.sin(rad)

    -- Translate point back to origin
    local dx = x - ox
    local dy = y - oy

    -- Rotate
    local rx = dx * cos - dy * sin
    local ry = dx * sin + dy * cos

    -- Translate back
    return rx + ox, ry + oy
end

-- Initialize and determine some values
termWidth, termHeight = term.getSize()
termMidX = math.floor(termWidth / 2)
termMidY = math.floor(termHeight / 2)
local yaw = 0
local hasGeoDetector = ensureGeoDetector() ~= false
local hasPlayerDetector = ensurePlayerDetector() ~= false
local backPeripheral = ensureGeoDetector(backPeripheral)
assert(checkIsGeoDetector(backPeripheral))

-- Create toggle button
toggleButtonWidth = 6
toggleButtonheight = 2
toggleButton = GUI.createButton("scan",
    termWidth - toggleButtonWidth,
    termHeight - toggleButtonheight,
    toggleButtonWidth, toggleButtonheight,
    colors.white, colors.red,
    colors.white, colors.green
)
toggleButton.toggle = true

term.clear()
i = 0
while true do
    if toggleButton.state == true then
        i = i + 1
        if hasPlayerDetector and i % 8 == 0 then
            backPeripheral = ensurePlayerDetector(backPeripheral)
            local playerInfo = getPlayerInfo(backPeripheral)
            yaw = playerInfo.yaw
        end
        backPeripheral = ensureGeoDetector()
        ores = scanAndFilter(backPeripheral)
        term.setBackgroundColor(colors.black)
        term.clear()
        for key, value in pairs(ores) do
            -- rotate
            x, y = rotatePoint(value.x, value.z, 0, 0, -yaw)
            -- round and diff
            x = termMidX - math.floor(x)
            y = termMidY - math.floor(y)
            local textColor = colors.red
            local backgroundColor = colors.black
            local text
            if value.y == 0 then
                textColor = colors.lime
                text = "O"
            elseif value.y < 0 and value.y > -3 then
                textColor = colors.green
                text = "v"
            elseif value.y > 0 and value.y < 3 then
                textColor = colors.green
                text = "^"
            elseif value.y < -3 and value.y > -10 then
                textColor = colors.yellow
                text = "v"
            elseif value.y > 3 and value.y < 10 then
                textColor = colors.yellow
                text = "^"
            elseif value.y < -10 and value.y > -32 then
                textColor = colors.orange
                text = "v"
            elseif value.y > 10 and value.y < 32 then
                textColor = colors.orange
                text = "^"
            end
            if text ~= nil then
                backgroundColor = oreAllowList[value.name]
                if GUI._2Dhit(x, y, 0, 0, termWidth, termHeight) then
                    GUI.drawText(term, x, y, textColor, backgroundColor, text)
                    GUI.drawText(term, 0, 0, textColor, backgroundColor, text)
                end
            end
        end
        GUI.drawText(term, termMidX, termMidY, colors.black, colors.white, " ") -- Indicate player position
    end
    
    GUI.drawAll(false)
    os.startTimer(0.2) -- Throw in a timer to quickly continue if there are no events queued
    events = {os.pullEvent()}
    GUI.handleEvent(events)
    -- sleep(0.1)
end